// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using garge_api.Models;

#nullable disable

namespace garge_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408192000_AddUniqueSwitchNameAndDeduplicateSocket")]
    partial class AddUniqueSwitchNameAndDeduplicateSocket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
