// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using garge_api.Models;

#nullable disable

namespace garge_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408134000_ReattachBatteryHealthToVoltageSensor")]
    partial class ReattachBatteryHealthToVoltageSensor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // No schema changes in this migration — model snapshot is identical to the previous migration.
        }
    }
}
